#!/bin/bash

# Set up the environment 



# Step 1: Download Kafka

wget https://archive.apache.org/dist/kafka/2.8.0/kafka_2.12-2.8.0.tgz


# Step 2: Extract Kafka

tar -xzf kafka_2.12-2.8.0.tgz



# Step 3: Start database server

start_mysql


# Step 4: Connect to the database server, using the command below. Make sure you # use the password given to you when the MySQL server starts. Please make a note # or record of the password because you will need it later.

mysql --host=127.0.0.1 --port=3306 --user=root --password=Mjk0NDQtcnNhbm5h


# Step 5: Create a database named tolldata

## At the ‘mysql>’ prompt, run the command below
create database tolldata;


# Step 6: Create a table named livetolldata with the schema to store the data generated by the traffic simulator.
# This is the table where you would store all the streamed data that comes from Kafka.
# Each row is a record of when a vehicle has passed through 
# a certain toll plaza along with its type and anonymized id.

use tolldata;

create table livetolldata(timestamp datetime,vehicle_id int,vehicle_type char(15),toll_plaza_id smallint);


# Step 7: Disconnect from MySQL server

exit




# Step 8: Install the necessary python module to work with Kafka and database 

python3 -m pip install kafka-python

python3 -m pip install mysql-connector-python==8.0.31

