create or replace TABLE CRIME_LITE (
	INCIDENT_NUMBER VARCHAR(15) NOT NULL,
	OFFENSE_CODE VARCHAR(10) NOT NULL,
	OFFENSE_CODE_GROUP VARCHAR(255) NOT NULL,
	OFFENSE_DESCRIPTION VARCHAR(255),
	DISTRICT VARCHAR(10),
	SHOOTING VARCHAR(2),
	OCCURRED_ON_DATE TIMESTAMP_NTZ(9) NOT NULL,
	YEAR NUMBER(38,0) NOT NULL,
	MONTH NUMBER(38,0) NOT NULL,
	DAY_OF_WEEK VARCHAR(20) NOT NULL,
	HOUR NUMBER(38,0) NOT NULL,
	UCR_PART VARCHAR(10),
	STREET VARCHAR(255)
);

CREATE OR Replace STAGE "DE_DEMO"."PUBLIC"."MY_CSV_STAGE";

CREATE OR Replace FILE FORMAT "DE_DEMO"."PUBLIC".CRIME_DEMO
TYPE = 'CSV' 
COMPRESSION = 'GZIP' 
FIELD_DELIMITER = ',' 
RECORD_DELIMITER = '\n' 
SKIP_HEADER = 1 
FIELD_OPTIONALLY_ENCLOSED_BY = '\042' 
TRIM_SPACE = TRUE 
ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE 
ESCAPE = 'NONE' 
ESCAPE_UNENCLOSED_FIELD = '\134' 
DATE_FORMAT = 'AUTO' 
TIMESTAMP_FORMAT = 'dd/mm/yyyy HH24:MI' 
NULL_IF = ('NULL');
